name: prometheus-juju-backup-all-exporter
base: core22
adopt-info: prometheus-juju-backup-all-exporter
summary: collects backup results and exports them as metrics
description: |
  The prometheus-juju-backup-all-exporter is a snap for collecting backup
  results from charm-juju-backup-all, and exporting those results as Prometheus
  metrics. The metrics are expected to be used with Prometheus. The exporter
  service currently only supports HTTP, so the communication is not encrypted.
grade: stable
confinement: strict

apps:
  prometheus-juju-backup-all-exporter:
    daemon: simple
    install-mode: disable
    restart-condition: on-abnormal
    command: bin/prometheus-juju-backup-all-exporter
    plugs:
      - network-bind

parts:
  prometheus-juju-backup-all-exporter:
    source: .
    plugin: python
    python-requirements: [./requirements.txt]
    override-build: |
      snapcraftctl build
      echo "Version: $(python3 setup.py --version)"
      snapcraftctl set-version "$(python3 setup.py --version)"
