name: Functionality validation

on:
  pull_request_review:
    types: [ submitted ]
    branches: [ main ]

jobs:
  func:
    name: Functional tests
    runs-on: ubuntu-latest
    if: >-
      github.event.review.state == 'approved'
      || github.event.review.body == 'recheck'
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install tox
      run: pip install "tox < 4"  #tox has breaking changes in major version 4
    - name: Set up LXD
      uses: canonical/setup-lxd@90d76101915da56a42a562ba766b1a77019242fd
    - name: Install snapcraft
      run: sudo snap install snapcraft --classic
    - name: Build and run functional tests
      run: make functional
