name: Basic validation

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]

jobs:
  lint-unit:
    name: Lint and unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Run lint tests
      run: make lint
    - name: Run unit tests
      run: make unittests
    - name: Save PR number to file
      run: echo ${{ github.event.number }} > PR_NUMBER.txt
    - name: Archive PR number
      uses: actions/upload-artifact@v3
      with:
        name: PR_NUMBER
        path: PR_NUMBER.txt
    - name: Save coverage report
      run: |
        report_root="/home/runner/work/prometheus-juju-backup-all-exporter/prometheus-juju-backup-all-exporter/report/"
        cp ${report_root}/coverage.xml cov.xml

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: ./cov.xml
